name: Destroy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete Documents
        run: |
          for file in *.yml; do
            [ -f "$file" ] || continue
            document_name=$(basename "$file" .yml)
            
            if aws ssm describe-document --name "$document_name" >/dev/null 2>&1; then
              echo "Deleting $document_name"
              aws ssm delete-document --name "$document_name"
            else
              echo "Document $document_name does not exist"
            fi
          done